### ISSUE TITLE
Facebook login error

### ISSUE THREAD

**Issue by AxiK101** [alexstyl/Memento-Calendar#127]
This is what i get everytime i try
![](http://i.imgur.com/603Caqe.png)

_Sent from my Sony F3211 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by alexstyl** [comment]
Closing this, as it was fixed by https://github.com/alexstyl/Memento-Calendar/pull/135. Update pushing to the Play store shortly :)

**Comment by AxiK101** [comment]
Ευχαριστώ!

_Sent from my Sony F3211 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by alexstyl** [comment]
Glad it works for you. A lot of new stuff are coming shortly too 😉
