### ISSUE TITLE
Bug report of Memento Calendar Application

### ISSUE THREAD

**Issue by Megaisabela** [alexstyl/Memento-Calendar#174]
#### Expected behavior<br>
<br>
I really hope to log into Facebook without any problems.

#### Actual behavior<br>
The app hangs on the loading screen after I log into Facebook.
<br>

#### How to reproduce<br>
<br>
* Download the Memento Calendar app on playstore<br>
* Launch application<br>
* Click on on the three lines on the top left side<br>
* Select Facebook friends<br>
* Enter an email or phone number and password and log in<br>
* Then choose Oke button<br>
<br>
* Device used: Samsung Grand prime SM-G530<br>
<br>
* Operating System: Android version 4.4.4<br>
<br>
* Application version:11.2<br>
<br>
#### Recording Of The Bug<br>
https://youtu.be/2Na1lVmLnPw

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@gentasteem/bug-report-of-memento-calendar-application">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by alexstyl** [comment]
Closing, as this issue has been resolved.
