### ISSUE TITLE
Icon/Logo Proposal

### ISSUE THREAD

**Issue by Tobaloidee** [alexstyl/Memento-Calendar#175]
Hi Sir @alexstyl ,

I am a designer and I did some tweaking in the existing logo that you might like. I saw the icon and I thought it's missing a mark for Memento that's why I incorporate the initial which is "M". I'm giving this for free if you want.

![memento](https://user-images.githubusercontent.com/36028424/37862585-7497d016-2f8a-11e8-9cf5-a2d46fe150fb.png)

Best regards,
Tobaloidee

**Comment by alexstyl** [comment]
Hi @Tobaloidee, thank you for your icon. I am quite happy with the current icon by @qqipp. I do like your idea of using the 'm' letter, but I don't think it works nicely in its current form. The m in your icon looks like a spider to me 😅
