### ISSUE TITLE
Excess spacing on first row

### ISSUE THREAD

**Issue by jeremyrempel** [alexstyl/Memento-Calendar#185]
![screenshot_20180527-020133](https://user-images.githubusercontent.com/1776510/40585644-38df2598-6152-11e8-8c69-0654789e35ac.png)

See attached screenshot. Between the first and second row theres a large blank space.

Environment:
Pixel 2
Android P (PP2.180412.013)

**Comment by alexstyl** [comment]
Thank you for the report. This is a known issue and has been resolved on the `develop` branch. it will be fixed in the next version :)
