### ISSUE TITLE
How about putting a copy of  setting up the project  into readme.md file？

### ISSUE THREAD

**Issue by siegeout** [alexstyl/Memento-Calendar#70]
It will be more convenient for users,to some extent this is also design for ux.

**Comment by alexstyl** [comment]
A guide on how to setup the project can be found int he [wiki](https://github.com/alexstyl/Memento-Calendar/wiki/How-to-contribute)

Isn't that the go to place for that? 🤔

**Comment by siegeout** [comment]
Because there are no extra settings for other open source apps in usual,we may ignore the wiki.When it  causes compile error,we will try some times,finally we just come back your this  site for an answer.
This spends a lot. A guide should be put in the wiki surely, but it would better to have a notice in readme for error or what is necessary.
